// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_gin/dal/model"
)

func newKlznSites(db *gorm.DB) klznSites {
	_klznSites := klznSites{}

	_klznSites.klznSitesDo.UseDB(db)
	_klznSites.klznSitesDo.UseModel(&model.KlznSites{})

	tableName := _klznSites.klznSitesDo.TableName()
	_klznSites.ALL = field.NewAsterisk(tableName)
	_klznSites.ID = field.NewInt32(tableName, "id")
	_klznSites.TargetURL = field.NewString(tableName, "target_url")
	_klznSites.URL = field.NewString(tableName, "url")
	_klznSites.Logo = field.NewString(tableName, "logo")
	_klznSites.Icon = field.NewString(tableName, "icon")
	_klznSites.TopURL = field.NewString(tableName, "top_url")
	_klznSites.Name = field.NewString(tableName, "name")
	_klznSites.Title = field.NewString(tableName, "title")
	_klznSites.Keywords = field.NewString(tableName, "keywords")
	_klznSites.Description = field.NewString(tableName, "description")
	_klznSites.Kw = field.NewString(tableName, "kw")
	_klznSites.Tag = field.NewString(tableName, "tag")
	_klznSites.Content = field.NewString(tableName, "content")
	_klznSites.Status = field.NewInt32(tableName, "status")
	_klznSites.CreatedAt = field.NewTime(tableName, "created_at")
	_klznSites.UpdatedAt = field.NewTime(tableName, "updated_at")
	_klznSites.Sort = field.NewInt32(tableName, "sort")
	_klznSites.IsRecommend = field.NewInt32(tableName, "is_recommend")

	_klznSites.fillFieldMap()

	return _klznSites
}

type klznSites struct {
	klznSitesDo

	ALL         field.Asterisk
	ID          field.Int32
	TargetURL   field.String // 捕获到的目标URL
	URL         field.String // 网站URL
	Logo        field.String // 网站Logo
	Icon        field.String // 网站图标
	TopURL      field.String // 网站顶级域名
	Name        field.String // 网站名称
	Title       field.String // 网站标题
	Keywords    field.String // 网站关键字
	Description field.String // 网站描述
	Kw          field.String // 当前搜索关键字
	Tag         field.String // 标签
	Content     field.String // 内容丰富描述
	Status      field.Int32  // 状态；1：正常；2：删除
	CreatedAt   field.Time   // 添加时间
	UpdatedAt   field.Time   // 更新时间
	Sort        field.Int32  // 排序；正序
	IsRecommend field.Int32  // 是否推荐；1：是；2：否

	fieldMap map[string]field.Expr
}

func (k klznSites) Table(newTableName string) *klznSites {
	k.klznSitesDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k klznSites) As(alias string) *klznSites {
	k.klznSitesDo.DO = *(k.klznSitesDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *klznSites) updateTableName(table string) *klznSites {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt32(table, "id")
	k.TargetURL = field.NewString(table, "target_url")
	k.URL = field.NewString(table, "url")
	k.Logo = field.NewString(table, "logo")
	k.Icon = field.NewString(table, "icon")
	k.TopURL = field.NewString(table, "top_url")
	k.Name = field.NewString(table, "name")
	k.Title = field.NewString(table, "title")
	k.Keywords = field.NewString(table, "keywords")
	k.Description = field.NewString(table, "description")
	k.Kw = field.NewString(table, "kw")
	k.Tag = field.NewString(table, "tag")
	k.Content = field.NewString(table, "content")
	k.Status = field.NewInt32(table, "status")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.Sort = field.NewInt32(table, "sort")
	k.IsRecommend = field.NewInt32(table, "is_recommend")

	k.fillFieldMap()

	return k
}

func (k *klznSites) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *klznSites) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 18)
	k.fieldMap["id"] = k.ID
	k.fieldMap["target_url"] = k.TargetURL
	k.fieldMap["url"] = k.URL
	k.fieldMap["logo"] = k.Logo
	k.fieldMap["icon"] = k.Icon
	k.fieldMap["top_url"] = k.TopURL
	k.fieldMap["name"] = k.Name
	k.fieldMap["title"] = k.Title
	k.fieldMap["keywords"] = k.Keywords
	k.fieldMap["description"] = k.Description
	k.fieldMap["kw"] = k.Kw
	k.fieldMap["tag"] = k.Tag
	k.fieldMap["content"] = k.Content
	k.fieldMap["status"] = k.Status
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["sort"] = k.Sort
	k.fieldMap["is_recommend"] = k.IsRecommend
}

func (k klznSites) clone(db *gorm.DB) klznSites {
	k.klznSitesDo.ReplaceDB(db)
	return k
}

type klznSitesDo struct{ gen.DO }

func (k klznSitesDo) Debug() *klznSitesDo {
	return k.withDO(k.DO.Debug())
}

func (k klznSitesDo) WithContext(ctx context.Context) *klznSitesDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k klznSitesDo) ReadDB() *klznSitesDo {
	return k.Clauses(dbresolver.Read)
}

func (k klznSitesDo) WriteDB() *klznSitesDo {
	return k.Clauses(dbresolver.Write)
}

func (k klznSitesDo) Clauses(conds ...clause.Expression) *klznSitesDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k klznSitesDo) Returning(value interface{}, columns ...string) *klznSitesDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k klznSitesDo) Not(conds ...gen.Condition) *klznSitesDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k klznSitesDo) Or(conds ...gen.Condition) *klznSitesDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k klznSitesDo) Select(conds ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k klznSitesDo) Where(conds ...gen.Condition) *klznSitesDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k klznSitesDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *klznSitesDo {
	return k.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (k klznSitesDo) Order(conds ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k klznSitesDo) Distinct(cols ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k klznSitesDo) Omit(cols ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k klznSitesDo) Join(table schema.Tabler, on ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k klznSitesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k klznSitesDo) RightJoin(table schema.Tabler, on ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k klznSitesDo) Group(cols ...field.Expr) *klznSitesDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k klznSitesDo) Having(conds ...gen.Condition) *klznSitesDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k klznSitesDo) Limit(limit int) *klznSitesDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k klznSitesDo) Offset(offset int) *klznSitesDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k klznSitesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *klznSitesDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k klznSitesDo) Unscoped() *klznSitesDo {
	return k.withDO(k.DO.Unscoped())
}

func (k klznSitesDo) Create(values ...*model.KlznSites) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k klznSitesDo) CreateInBatches(values []*model.KlznSites, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k klznSitesDo) Save(values ...*model.KlznSites) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k klznSitesDo) First() (*model.KlznSites, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KlznSites), nil
	}
}

func (k klznSitesDo) Take() (*model.KlznSites, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KlznSites), nil
	}
}

func (k klznSitesDo) Last() (*model.KlznSites, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KlznSites), nil
	}
}

func (k klznSitesDo) Find() ([]*model.KlznSites, error) {
	result, err := k.DO.Find()
	return result.([]*model.KlznSites), err
}

func (k klznSitesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KlznSites, err error) {
	buf := make([]*model.KlznSites, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k klznSitesDo) FindInBatches(result *[]*model.KlznSites, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k klznSitesDo) Attrs(attrs ...field.AssignExpr) *klznSitesDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k klznSitesDo) Assign(attrs ...field.AssignExpr) *klznSitesDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k klznSitesDo) Joins(fields ...field.RelationField) *klznSitesDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k klznSitesDo) Preload(fields ...field.RelationField) *klznSitesDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k klznSitesDo) FirstOrInit() (*model.KlznSites, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KlznSites), nil
	}
}

func (k klznSitesDo) FirstOrCreate() (*model.KlznSites, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KlznSites), nil
	}
}

func (k klznSitesDo) FindByPage(offset int, limit int) (result []*model.KlznSites, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k klznSitesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k klznSitesDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k klznSitesDo) Delete(models ...*model.KlznSites) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *klznSitesDo) withDO(do gen.Dao) *klznSitesDo {
	k.DO = *do.(*gen.DO)
	return k
}
