// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKlznSite = "sun_klzn_site"

// KlznSite mapped from table <sun_klzn_site>
type KlznSite struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TargetURL   string    `gorm:"column:target_url;not null" json:"target_url"`                           // 捕获到的目标URL
	URL         string    `gorm:"column:url;not null" json:"url"`                                         // 网站URL
	Logo        string    `gorm:"column:logo;not null" json:"logo"`                                       // 网站Logo
	Icon        string    `gorm:"column:icon;not null" json:"icon"`                                       // 网站图标
	TopURL      string    `gorm:"column:top_url;not null" json:"top_url"`                                 // 网站顶级域名
	Name        string    `gorm:"column:name;not null" json:"name"`                                       // 网站名称
	Title       string    `gorm:"column:title;not null" json:"title"`                                     // 网站标题
	Keywords    string    `gorm:"column:keywords;not null" json:"keywords"`                               // 网站关键字
	Description string    `gorm:"column:description;not null" json:"description"`                         // 网站描述
	Kw          string    `gorm:"column:kw;not null" json:"kw"`                                           // 当前搜索关键字
	Tag         string    `gorm:"column:tag;not null" json:"tag"`                                         // 标签
	Content     string    `gorm:"column:content" json:"content"`                                          // 内容丰富描述
	Status      int32     `gorm:"column:status;not null" json:"status"`                                   // 状态；1：正常；2：删除
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`                           // 添加时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	Sort        int32     `gorm:"column:sort;not null;default:1" json:"sort"`                             // 排序；正序
	IsRecommend int32     `gorm:"column:is_recommend;not null;default:2" json:"is_recommend"`             // 是否推荐；1：是；2：否
}

// TableName KlznSite's table name
func (*KlznSite) TableName() string {
	return TableNameKlznSite
}
