// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKlznMovie = "sun_klzn_movie"

// KlznMovie mapped from table <sun_klzn_movie>
type KlznMovie struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增ID
	URL   string `gorm:"column:url;not null" json:"url"`                    // 地址
	Title string `gorm:"column:title;not null" json:"title"`                // 标题
	/*
		关键字

	*/
	Keyword     string    `gorm:"column:keyword;not null" json:"keyword"`
	Description string    `gorm:"column:description;not null" json:"description"`                         // 描述
	Content     string    `gorm:"column:content;not null" json:"content"`                                 // 内容
	Hot         int32     `gorm:"column:hot;not null" json:"hot"`                                         // 热度值
	Status      bool      `gorm:"column:status;not null" json:"status"`                                   // 状态；1：正常；2：删除
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`                           // 添加时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName KlznMovie's table name
func (*KlznMovie) TableName() string {
	return TableNameKlznMovie
}
