// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // ID
	Name        string `gorm:"column:name;not null" json:"name"`                  // 姓名
	Age         int32  `gorm:"column:age;not null" json:"age"`                    // 年龄
	Description string `gorm:"column:description;not null" json:"description"`    // 其他情况下的描述
	State       int32  `gorm:"column:state;not null;default:1" json:"state"`      // 状态；1：正常；2：删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
