mysql:
  host: "47.116.2.14"
  port: 3306
  username: "sunqiaoyu"
  passwd: "s13166956607"
  prefix: ""
  db: "project"

redis:
  host: "47.116.2.14"
  db: 0
  passwd: ""

log:
  path: "./logs/"
  errLogFileName: "err_log"
  appLogFileName: "app"
  maxAge: 30  #天为单位
  maxBack: 30